version: "3.9"

services:
  app:
    build: .
    container_name: secure-crud-app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - private_net

  db:
    image: mongo:7
    container_name: secure-crud-db
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - private_net

  proxy:
    image: nginx:alpine
    container_name: secure-crud-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - private_net

networks:
  private_net:
    driver: bridge

volumes:
  mongo_data: